// Generated by scripts/prepare-room-assets.mjs; original square frames retained.
export const ROOM_ASSET_FRAMES: Readonly<Record<string, { left: number; top: number; width: number; height: number; canvas: number }>> = {
  "dresser": {
    "left": 8,
    "top": 51,
    "width": 284,
    "height": 199,
    "canvas": 300
  },
  "cart": {
    "left": 8,
    "top": 19,
    "width": 284,
    "height": 263,
    "canvas": 300
  },
  "pouf": {
    "left": 8,
    "top": 74,
    "width": 284,
    "height": 153,
    "canvas": 300
  },
  "plant": {
    "left": 8,
    "top": 20,
    "width": 284,
    "height": 261,
    "canvas": 300
  },
  "basket": {
    "left": 8,
    "top": 58,
    "width": 284,
    "height": 184,
    "canvas": 300
  },
  "side-table": {
    "left": 17,
    "top": 8,
    "width": 266,
    "height": 284,
    "canvas": 300
  },
  "lamp": {
    "left": 93,
    "top": 8,
    "width": 115,
    "height": 284,
    "canvas": 300
  },
  "paw-pouf": {
    "left": 8,
    "top": 72,
    "width": 284,
    "height": 156,
    "canvas": 300
  },
  "shelf-fillers": {
    "left": 8,
    "top": 80,
    "width": 284,
    "height": 140,
    "canvas": 300
  },
  "shelf-ribbons": {
    "left": 8,
    "top": 71,
    "width": 284,
    "height": 159,
    "canvas": 300
  },
  "shelf-stickers": {
    "left": 8,
    "top": 78,
    "width": 284,
    "height": 145,
    "canvas": 300
  },
  "figurine-shelf": {
    "left": 8,
    "top": 71,
    "width": 284,
    "height": 159,
    "canvas": 300
  },
  "picture": {
    "left": 8,
    "top": 26,
    "width": 284,
    "height": 248,
    "canvas": 300
  },
  "board": {
    "left": 8,
    "top": 53,
    "width": 284,
    "height": 195,
    "canvas": 300
  },
  "mirror": {
    "left": 15,
    "top": 8,
    "width": 271,
    "height": 284,
    "canvas": 300
  },
  "organizer": {
    "left": 8,
    "top": 33,
    "width": 284,
    "height": 234,
    "canvas": 300
  },
  "rug-oval": {
    "left": 8,
    "top": 100,
    "width": 284,
    "height": 100,
    "canvas": 300
  },
  "rug-flower": {
    "left": 8,
    "top": 92,
    "width": 284,
    "height": 117,
    "canvas": 300
  },
  "rug-cloud": {
    "left": 8,
    "top": 78,
    "width": 284,
    "height": 144,
    "canvas": 300
  },
  "rug-donut": {
    "left": 8,
    "top": 81,
    "width": 284,
    "height": 139,
    "canvas": 300
  },
  "garland": {
    "left": 8,
    "top": 176,
    "width": 464,
    "height": 129,
    "canvas": 480
  },
  "gift-box": {
    "left": 8,
    "top": 54,
    "width": 284,
    "height": 192,
    "canvas": 300
  }
};
