import { expect, test } from '@playwright/test';

test('M4 diagnose sticker input after Mix with pearl overlay and resized decor playfield', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/phaser-studio.html?lang=ru');
  await expect(page.locator('[data-sandbox-canvas]')).toHaveAttribute('data-phaser-ready', 'true');
  await page.locator('[data-shape="heart"]').click();
  await page.locator('[data-action="shape-continue"]').click();
  await page.locator('[data-action="paint-continue"]').click();
  await page.locator('[data-mixin="pearls"]').click();
  let box = await page.locator('[data-sandbox-canvas]').boundingBox();
  if (!box) throw new Error('Missing playfield');
  await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  await page.locator('[data-action="mixin-continue"]').click();
  box = await page.locator('[data-sandbox-canvas]').boundingBox();
  if (!box) throw new Error('Missing Mix playfield');
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  for (let i = 0; i < 22; i++) await page.mouse.move(x + (i % 2 ? -65 : 65), y, { steps: 3 });
  await page.mouse.up();
  await expect(page.locator('[data-action="mix-continue"]')).toBeEnabled();
  await page.locator('[data-action="mix-continue"]').click();
  await page.locator('[data-decor-section="stickers"]').click();
  box = await page.locator('[data-sandbox-canvas]').boundingBox();
  if (!box) throw new Error('Missing Decor playfield');
  const cx = box.x + box.width / 2;
  const cy = box.y + box.height / 2;
  const before = await page.evaluate(({ cx, cy }) => {
    const canvas = document.querySelector<HTMLCanvasElement>('[data-sandbox-canvas]')!;
    const rect = canvas.getBoundingClientRect();
    const top = document.elementFromPoint(cx, cy);
    const events: string[] = [];
    document.addEventListener('pointerdown', (event) => events.push('doc:'+ (event.target instanceof Element ? event.target.className : 'other')), { capture: true, once: true });
    canvas.addEventListener('pointerdown', (event) => events.push('canvas:'+event.clientX+','+event.clientY), { once: true });
    (window as Window & { __studioPointerEvents?: string[] }).__studioPointerEvents = events;
    return { cx, cy, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, intrinsic: [canvas.width, canvas.height], css: [canvas.clientWidth, canvas.clientHeight], inline: canvas.getAttribute('style'), top: top instanceof Element ? top.outerHTML.slice(0, 240) : 'none' };
  }, { cx, cy });
  console.log('REAL STUDIO DECOR HIT INPUT', JSON.stringify(before));
  await page.mouse.click(cx, cy);
  const after = await page.evaluate(() => ({ events: (window as Window & { __studioPointerEvents?: string[] }).__studioPointerEvents, count: document.querySelector('[data-sandbox-app]')?.getAttribute('data-decor-sticker-count'), layer: document.querySelector('[data-sandbox-canvas]')?.getAttribute('style') }));
  console.log('REAL STUDIO DECOR AFTER CLICK', JSON.stringify(after));
  expect(after.events?.some((event) => event.startsWith('canvas:')), 'A real DOM pointerdown must reach the Phaser canvas').toBe(true);
  expect(after.count, 'The real Phaser studio must author the sticker').toBe('1');
});
